### ISSUE TITLE
The addon won't start after updating to the newest version.

### ISSUE THREAD

**Issue by EugeneTarasenko** [Ambriel/advanced_copy_fields#3] opened 2023-12-23 18:58 UTC
<img width="612" alt="Screen Shot 2023-12-23 at 20 56 58" src="https://github.com/Ambriel/advanced_copy_fields/assets/87163666/ee81c11b-07a2-482c-90f3-219ab90aa12c">

```
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 5.14.2 PyQt 5.14.1
Platform: macOS-12.7.2-x86_64-i386-64bit
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-12-23 16:47:13

When loading Advanced Copy Fields:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "/Users/eugen/Library/Application Support/Anki2/addons21/1898445115/__init__.py", line 1, in <module>
    from . import advanced_copy_fields
  File "/Users/eugen/Library/Application Support/Anki2/addons21/1898445115/advanced_copy_fields.py", line 18, in <module>
    from PyQt6 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt6'

```

**Comment by Lilneo786** [comment] 2023-12-23 19:28
You can try installing PyQt6 to resolve this issue.

`pip install PyQt6`

After installing PyQt6, restart Anki and see if the issue is resolved.

OR: 

Downgrade PyQt Version: If the add-on is not compatible with PyQt6, you may need to downgrade PyQt to a version that the add-on supports. You can uninstall PyQt6 and install an older version like PyQt5:

```
pip uninstall PyQt6
pip install PyQt5
```

**Comment by EugeneTarasenko** [comment] 2023-12-23 19:52
@Lilneo786  How can I install the previous version of the addon? It was working perfectly.

<img width="713" alt="Screen Shot 2023-12-23 at 21 07 38" src="https://github.com/Ambriel/advanced_copy_fields/assets/87163666/17e80a10-f385-43ff-a89e-f3748880078a">

**Comment by Lilneo786** [comment] 2023-12-23 20:00
remove 

and then https://changes.ankiweb.net/ to reinstall

**Comment by EugeneTarasenko** [comment] 2023-12-23 20:05
Could you please share the files for the previous version of the Advanced Copy Fields to install it from computer?

<img width="698" alt="Screen Shot 2023-12-23 at 22 02 43" src="https://github.com/Ambriel/advanced_copy_fields/assets/87163666/1a930e3c-2257-4b66-ae7d-366c96894764">

<img width="713" alt="292643146-17e80a10-f385-43ff-a89e-f3748880078a" src="https://github.com/Ambriel/advanced_copy_fields/assets/87163666/4727f76a-7d30-43d9-8cde-22687984fd5f">

**Comment by Lilneo786** [comment] 2023-12-23 20:12
https://apps.ankiweb.net/downloads/archive/
Has all the versions

I think this is the version you need:
https://github.com/ankitects/anki/releases?q=2.1.23&expanded=true

**Comment by Lilneo786** [comment] 2023-12-23 20:13
https://github.com/ankitects/anki/releases/download/23.10.1/anki-23.10.1-windows-qt6.exe

Is the direct link

**Comment by EugeneTarasenko** [comment] 2023-12-23 20:19
I meant the previous version of the Advanced Copy Fields addon, not Anki.
This one:
<img width="713" alt="Screen Shot 2023-12-23 at 21 07 38" src="https://github.com/Ambriel/advanced_copy_fields/assets/87163666/bbf40d42-f19c-40d9-9575-55e3ac421129">

**Comment by Lilneo786** [comment] 2023-12-23 20:34
Sorry for the misunderstanding. They have a fork for that version that isnt working for you and the instructions to download it is here: https://ankiweb.net/shared/info/287110490

can find the code here: https://github.com/andkinnamon/Advanced-Copy-Fields-Qt6

**Comment by Ambriel** [comment] 2023-12-26 02:02
Thank you for helping @EugeneTarasenko EugeneTarasenko on this, @Lilneo786. I would have had to do some research since I've not been active on this project for a while. I'll update the documentation on my page to help others in the future. 

Python is a pretty flexible language. I'm thinking there should be a way to implement simultaneous QT5 and QT6 support, but I'd have to look at it when I get more free time unless someone beats me to it.

**Comment by Ambriel** [comment] 2023-12-26 02:03
Thank you for helping @EugeneTarasenko on this, @Lilneo786. I would have had to do some research since I've not been active on this project for a while. I'll update the documentation on my page to help others in the future. 

Python is a pretty flexible language. I am thinking there should be a way to implement simultaneous QT5 and QT6 support, but I'd have to look at it when I get more free time unless someone beats me to it.

**Comment by EugeneTarasenko** [comment] 2023-12-26 02:08
Thank you for providing the links. However, could you please explain what steps I should take with these files to install them into Anki? None of the files can be selected after clicking the 'Install from file...' button.

<img width="698" alt="292643592-1a930e3c-2257-4b66-ae7d-366c96894764" src="https://github.com/Ambriel/advanced_copy_fields/assets/87163666/8db2d1e3-691b-4332-8d32-40654c01004c">

<img width="827" alt="Screen Shot 2023-12-26 at 04 04 15" src="https://github.com/Ambriel/advanced_copy_fields/assets/87163666/bdd83ad1-d216-4ab9-b3ec-87990fba550f">

**Comment by Lilneo786** [comment] 2023-12-26 02:20
You have to file compile the file, but I highly recommend reading the "README.MD" file first for accurate instructions.

**Comment by EugeneTarasenko** [comment] 2023-12-26 02:26
@Lilneo786  There is no information inside the "README.MD" except these two lines of text:



# AdvancedCopyFields
Anki 2.1.x Plugin for performing various field copy/move operations

**Comment by Ambriel** [comment] 2023-12-26 02:27
@EugeneTarasenko, Remove the contents (not the folder itself) of the Advanced Copy Fields already on your computer and then paste the unzipped contents of the old release into it.

Make sure you don't copy/cut any folder in which the old files are enclosed, just the files.

You will have to restart Anki for the changes to take place.

Note: If you need to find the folder where ACF is stored, you will click on the add-on name from within the **Add-ons** dialog, and click "View Files"

**Comment by Ambriel** [comment] 2023-12-26 02:28
And you can remove the manifest file, I believe, to stop it from trying to update.

**Comment by EugeneTarasenko** [comment] 2023-12-26 02:43
> @EugeneTarasenko, Remove the contents (not the folder itself) of the Advanced Copy Fields already on your computer and then paste the unzipped contents of the old release into it.
> 
> Make sure you don't copy/cut any folder in which the old files are enclosed, just the files.
> 
> You will have to restart Anki for the changes to take place.
> 
> Note: If you need to find the folder where ACF is stored, you will click on the add-on name from within the **Add-ons** dialog, and click "View Files"

@Ambriel Unfortunately, Anki throws an error upon startup after following the steps you provided.:

<img width="532" alt="Screen Shot 2023-12-26 at 04 39 17" src="https://github.com/Ambriel/advanced_copy_fields/assets/87163666/3010e0dc-1481-4afc-bba0-3f51797b2b49">

**Comment by Ambriel** [comment] 2023-12-26 03:02
It doesn't look like that is the correct version. It's making references to PyQt6 which is the more recent update.
[advanced_copy_fields-v0.3.0.zip](https://github.com/Ambriel/advanced_copy_fields/files/13768209/advanced_copy_fields-v0.3.0.zip)

**Comment by EugeneTarasenko** [comment] 2023-12-26 03:07
@Ambriel, I downloaded the files exactly from the link you provided. This one:

<img width="1160" alt="Screen Shot 2023-12-26 at 05 06 41" src="https://github.com/Ambriel/advanced_copy_fields/assets/87163666/5d0cd2f5-ba75-432d-b4db-3e0974f171b0">

**Comment by EugeneTarasenko** [comment] 2023-12-26 03:09
How can I compile the source code to install it from a file myself? Could you please provide some information on this?

**Comment by Ambriel** [comment] 2023-12-26 03:10
Yep, you're right. Somewhere along time I started to mix in the PyQT6 libraries that are not on Anki. The older advanced_copy_fields.py is using PyWT5. I need to delete that release because it's not right.

Here, try replacing the file on your computer with the one in this package.

[advanced_copy_fields-v0.3.0.zip](https://github.com/Ambriel/advanced_copy_fields/files/13768241/advanced_copy_fields-v0.3.0.zip)

**Comment by EugeneTarasenko** [comment] 2023-12-26 03:15
@Ambriel 
Yes, it finally works correctly 🍾. Thank you very much for your help. I truly appreciate it.

**Comment by Ambriel** [comment] 2023-12-26 03:22
> @Ambriel Yes, it finally works correctly 🍾. Thank you very much for your help. I truly appreciate it.

You're welcome, and thank you! This, I'm sure, will also save some other people some drama. I'm working on creating the correct release for QT5

**Comment by EugeneTarasenko** [comment] 2023-12-26 21:48
@MAJMAJ-med 
1) Install the latest version of Advanced Copy Fields addon from AnkiWeb ([1898445115](https://ankiweb.net/shared/info/1898445115))
2) Find the location of the files of the addon on your computer:
<img width="653" alt="Screen Shot 2023-12-26 at 23 43 19" src="https://github.com/Ambriel/advanced_copy_fields/assets/87163666/dfaeb7f9-f118-47e8-a87c-95d931e111b5">

3) Replace the files with these ones: [advanced_copy_fields-v0.3.0.zip](https://github.com/Ambriel/advanced_copy_fields/files/13768241/advanced_copy_fields-v0.3.0.zip)
4) Restart Anki

**Comment by Ambriel** [comment] 2023-12-27 00:31
Awesome! Thank you for that @EugeneTarasenko! You're awesome!

Closing this thread. If any issues with something in the future, please open a new concern!

Thank you.

**Closed** 2023-12-27 00:32 UTC
